import { MovebankAttribute } from './builder.model';

export const INITIAL_MOVEBANK_ATTRIBUTES: MovebankAttribute[] = [
  // Study Attributes
  {
    key: 'name',
    entity: 'study',
    group: 'General',
    label: 'Study Name',
    type: 'text',
    value: 'Global Avian Migration',
    enabled: true,
  },
  {
    key: 'study_objective',
    entity: 'study',
    group: 'General',
    label: 'Study Objective',
    type: 'text',
    value: 'Tracking flight paths',
    enabled: false,
  },
  {
    key: 'main_location_lat',
    entity: 'study',
    group: 'Location',
    label: 'Main Location Latitude',
    type: 'number',
    minimum: -90,
    maximum: 90,
    value: 47.6,
    enabled: false,
  },

  // Individual Attributes
  {
    key: 'local_identifier',
    entity: 'individual',
    group: 'Identity',
    label: 'Animal Local ID',
    type: 'text',
    value: 'Bird-042',
    enabled: true,
  },
  {
    key: 'sex',
    entity: 'individual',
    group: 'Bio',
    label: 'Sex',
    type: 'select',
    enum: ['m', 'f', 'u'],
    value: 'm',
    enabled: true,
  },
  {
    key: 'animal_birth_hatch_year',
    entity: 'individual',
    group: 'Bio',
    label: 'Birth/Hatch Year',
    type: 'integer',
    minimum: 2000,
    maximum: 2026,
    value: 2023,
    enabled: false,
  },

  // Tag Attributes
  {
    key: 'model',
    entity: 'tag',
    group: 'Hardware',
    label: 'Tag Model',
    type: 'text',
    value: 'E-obs 100g',
    enabled: true,
  },
  {
    key: 'weight',
    entity: 'tag',
    group: 'Hardware',
    label: 'Tag Weight (g)',
    type: 'number',
    minimum: 0.1,
    maximum: 5000,
    value: 35,
    enabled: true,
  },
  {
    key: 'beacon_frequency',
    entity: 'tag',
    group: 'Telemetry',
    label: 'Beacon Frequency (MHz)',
    type: 'number',
    value: 150.1,
    enabled: false,
  },

  // Deployment Attributes
  {
    key: 'deploy_on_timestamp',
    entity: 'deployment',
    group: 'Timeline',
    label: 'Deployment Start Timestamp',
    type: 'date',
    value: '2026-06-01T00:00:00Z',
    enabled: true,
  },
  {
    key: 'animal_mass',
    entity: 'deployment',
    group: 'Measurements',
    label: 'Animal Mass (kg)',
    type: 'number',
    minimum: 0.01,
    maximum: 500,
    value: 4.5,
    enabled: true,
  },
  {
    key: 'attachment_type',
    entity: 'deployment',
    group: 'Method',
    label: 'Attachment Type',
    type: 'text',
    value: 'Harness',
    enabled: false,
  },

  // Event Attributes (Sensors & Telemetry)
  {
    key: 'gps_fix_type',
    entity: 'event',
    group: 'GPS',
    label: 'GPS Fix Type',
    type: 'text',
    value: '3D',
    enabled: true,
  },
  {
    key: 'gps_hdop',
    entity: 'event',
    group: 'GPS',
    label: 'GPS HDOP Precision',
    type: 'number',
    value: 1.2,
    enabled: false,
  },
  {
    key: 'eobs_accelerations_raw',
    entity: 'event',
    group: 'Sensors',
    label: 'Raw Accelerometer Data',
    type: 'boolean',
    value: true,
    enabled: true,
  },
  {
    key: 'barometric_pressure',
    entity: 'event',
    group: 'Environment',
    label: 'Barometric Pressure',
    type: 'number',
    value: 1013.25,
    enabled: false,
  },
];
